import type { Metadata } from 'next'

// These styles apply to every route in the application
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
 children,
}: {
  children: React.ReactNode
}) {
  return (
      <html lang="en">
      <head>
          <link rel="manifest" href="/manifest.json" />
          <link rel="apple-touch-icon" href="/icon-256x256.png"></link>
          <meta name="theme-color" content="#b8e986" />
      </head>
      <body className="bg-[#E5E1DE]  bg-contain">{children}</body>
      </html>
  )
}
